# Generated by Django 3.2.12 on 2022-02-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='harry_potter.jpg', upload_to='person'),
        ),
    ]
