# Generated by Django 3.2.12 on 2022-02-16 10:05

import Student_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_form', '0002_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='harry_potter.jpg', upload_to=Student_form.models.create_path),
        ),
    ]
